---
output:
  html_document:
    toc: true
    toc_depth: 5
    toc_float:
     collapsed: false
     smooth_scroll: false
---

<link rel="stylesheet" href="styles.css" type="text/css">

<br> 
My primary research interest is in statistical analysis of genomic data from high-throughput sequencing experiments.

<br>

## Publications 

+ *Diffsig: Associating Risk Factors With Mutational Signatures*, JE Park, M A. Smith, S C. Van Alsten, A Walens, D Wu, K A. Hoadley, M A. Troester, M I. Love, 2023, DOI: 10.1101/2023.02.09.527740

<br>

## Research Projects   
#### Recent  
+ `Diffsig`: Associating Risk Factors With Mutational Signatures
    + `Diffsig` is a  Bayesian hierarchical modeling R package that allows to estimate associations between multiple risk factors and mutational signatures. Our package allows to test associations on various types of risk factors - binary, continuous, categorical - 

#### Past
+ PM2.5 effect on brain function based on mouse RNAseq 
    + Analyze the effects of PM2.5 on mice brain function with RNAseq in areas including: Cerebellum, Cortex, etc.

+ Microbiome Project 2 - aVISTA + Cytoxan effect on breast cancer mice microbiome
    + Microbiome research based on mouse fecal samples DNA extraction and cutaneous humanbreast microbiome samples
    + Aim to determine the effects of aVISTA, Cyclophosphamide and Radiation Treatment effectson human and mice microbiome to understand the treatment effects on breast cancer.

+ Hypertension Research
    + Aim to determine the association of salt intake and hypertension, metabolic syndrome, andARB treatment effect from a 10K+ hypertension patients data attained from a K-MetS study

+ Myocardial Infarction(MI) - Stroke Research
    + Use Cox models to identify effect modification by demographics, stroke risk factors e.g. hypertension, diabetes, etc., and Charlson comorbidities

+ Hypertension Research
    + Aim to determine the association of salt intake and hypertension, metabolic syndrome, andARB treatment effect from a 10K+ hypertension patients data attained from a K-MetS study

+ Myocardial Infarction(MI) - Stroke Research
    + Survival analysis to identify effect modification by demographics, stroke risk factors e.g. hypertension, diabetes, etc., and Charlson comorbidities

+ Microbiome Project 1 - Workflow development of microbiome data analysis
    + Develop a comprehensive workflow for microbiome data analysis based on our analysis
    + Analyze 16S rRNA gene sequence data from a study to understand the effect of fructose consumption on mouse gut microbiome

+ Comparing clustering methods for single-cell RNA sequencing data (advisor: Davide Risso)
    + Compared clustering methods for analyzing Single-Cell RNA Sequencing Data
    + Performed data processing, simulation based on gamma-poisson distribution, normalization,dimensionality reduction (PCA) with R packages `scater`, `splatter`, `clusterExperiment`, etc.
